- name: Back up k3s application persistent volumes
  hosts: k3s
  become: true
  environment:
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  vars_files:
    - vars.yml
  tasks:
    - name: Back up apps
      ansible.builtin.include_role:
        name: backup_app
      vars:
        app_name: "{{ item.name }}"
        app_namespace: "{{ item.namespace }}"
      loop: "{{ apps }}"
