- name: Back up k3s application persistent volumes
  hosts: k3s
  become: true
  environment:
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  vars:
    app_name: homer
    app_namespace: homer
    # pvc_name: homer-assets
  tasks:
    - name: Get Deployment object
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        name: "{{ app_name }}"
        namespace: "{{ app_namespace }}"
      register: deployment

    - name: Back up PVC
      ansible.builtin.include_role:
        name: backup_pvc
      vars:
        pvc_name: "{{ item.persistentVolumeClaim.claimName }}"
        pvc_namespace: "{{ app_namespace }}"
      loop: "{{ deployment.resources[0].spec.template.spec.volumes }}"
