- name: Get PVC object
  kubernetes.core.k8s_info:
    api_version: v1
    kind: PersistentVolumeClaim
    name: "{{ pvc_name }}"
    namespace: "{{ pvc_namespace }}"
  register: pvc

- name: Get PV object
  kubernetes.core.k8s_info:
    api_version: v1
    kind: PersistentVolume
    name: "{{ pvc.resources[0].spec.volumeName }}"
  register: pv

- name: Create backup directory
  ansible.builtin.file:
    path: "/nfs/Backup/PVs/{{ pvc_name }}"
    state: directory

- name: Copy PV directory to backup directory
  ansible.builtin.copy:
    src: "{{ pv.resources[0].spec.hostPath.path }}"
    dest: "/nfs/Backup/PVs/{{ pvc_name }}/{{ ansible_date_time.date }}-{{ pvc_name}}"
    remote_src: yes
